#!/bin/sh

# This script is part of a collection of scripts to emulate creation
# of MRTG like pages while using RRDTool as a backend.
# This scripts iterates through all existing config files and calles
# the data collection and page generation script for each config. This
# script should be called by cron every 5 minutes.
# Additional infos (including a license notice) are at the end of this file.

errorExit () {
	echo Error: "$*"
	exit 1
}


BASECONFIG=/etc/mrtgLikeRRD/base.config

if [ ! -f ${BASECONFIG} ]; then
	errorExit "base config ${BASECONFIG} not found"
fi
. ${BASECONFIG}
if [ "x${TARGETDIR}" = x ]; then
	errorExit "TARGETDIR not defined"
fi
if [ ! -d "${TARGETDIR}" ]; then
	errorExit "'${TARGETDIR}' it not existing or is not a directory"
fi

cd ${TARGETDIR}
for TARGET in `ls -1 *.conf`; do
	#echo "Would call for '${TARGET}'"
	/usr/local/bin/mrtgLikeRRD ${TARGET}
done

# mrtgLikeRRD Copyright (C) 2021 Armin Fuerst (armin@fuerst.priv.at)
# This script is part of a collection of scripts to emulate creation
# of MRTG like pages while using RRDTool as a backend.
# This script collects values from sources, puts them into the RRD file
# and creates the page for this source.
# 
# mrtgLikeRRD simplifies adding additional sources to a collection
# of pages being created. It tries do create pages being as close
# as possible to MRTG.
# mrtgLikeRRD limits the functionality of RRDTool - RRDTool has many
# additional features you cannot use with mrtgLikeRRD. Especially the
# advantage of separating data collection from generation of the pages
# is not supported by mrtgLikeRRD.
# Following advantages of RRDTool are available to mrtgLikeRRD:
# + support of negative figures
# + support of float values (GAUGE)
# + support of missing values
#
# mrtgLikeRRD is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# mrtgLikeRRD is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with tempersensor.  If not, see <https://www.gnu.org/licenses/>.
#
#
# Why did I put the license notice at the bottom of the file?
# Because most of the time, when you open the file, the probability
# you want to know about the license is very little. If you open the
# file to learn about the license, it is still easy to find.
#
# Perhaps you want to have a look at the talk "Clean Coders Hate What 
# Happens to Your Code When You Use These Enterprise Programming Tricks"
# from Kevlin Henney at the NDC Conferences in London, January 16th-20th 
# 2017. While watching the whole talk is a good idea, starting at around 
# 27:50 provides some input what to put on the top of source code files.

